import React, { useState, useMemo } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { MockSubmission, UploadedContent, DataEntryRecord, PersonDomain } from '../../types';
import { PROGRAMMES } from '../../constants';
import * as XLSX from 'xlsx';
import { Logo } from '../../components/Logo';

const SUBMISSION_CATEGORIES = [
  { id: 'Data Entry', label: 'Incoming Registry' },
  { id: 'Exam Form', label: 'Exam Enrollment' },
  { id: 'Internship Letter', label: 'SIP Allotments' },
  { id: 'Leave Application', label: 'Attendance Audit' },
  { id: 'Grievance', label: 'Case Redressal' },
  { id: 'Feedback', label: 'Institutional Review' }
];

const REPOSITORY_CATEGORIES = [
  { id: 'Notice', label: 'Official Notice' },
  { id: 'Assignment', label: 'Assignment Question' },
  { id: 'Time-Table', label: 'Academic Time-Table' },
  { id: 'Question Bank', label: 'Subject Question Bank' },
  { id: 'Study', label: 'Study Material' },
  { id: 'Results', label: 'Examination Results' }
];

const NAV_ITEMS = [
  { id: 'overview', label: 'Infrastructure', icon: 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4' },
  { id: 'personnel', label: 'Personnel Hub', icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z' },
  { id: 'registry', label: 'Registry Hub', icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2' },
  { id: 'upload', label: 'Repository Sync', icon: 'M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12' },
  { id: 'timeline', label: 'Portal Control', icon: 'M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4' }
];


const getOfficialDocumentHTML = (entry: MockSubmission) => {
  const data = entry.data || {};
  let rows = '';

  Object.entries(data).forEach(([key, value]) => {
    if (value === null || value === undefined || value === '') return;

    const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()).trim();
    let valStr = 'N/A';
    
    if (['photoUrl', 'studentSignatureUrl'].includes(key)) {
      valStr = `<img src="${value as string}" style="max-height: 90px; max-width: 120px; border: 2px solid #000; padding: 2px;" alt="Image Artifact" />`;
    } else if (key === 'fileData') {
      valStr = 'File Attached in Digital System';
    } else if (typeof value === 'object') {
      if (Array.isArray(value)) {
        valStr = value.map(item => typeof item === 'object' ? Object.entries(item).filter(([k]) => !['id', 'key'].includes(k)).map(([k, v]) => `${k}: ${v}`).join(', ') : String(item)).join('<br/>');
      } else {
        valStr = Object.entries(value).map(([k, v]) => `${k}: ${v}`).join('<br/>');
      }
    } else {
      valStr = String(value);
    }
    
    rows += `
      <tr>
        <th style="padding: 12px; border: 1px solid #000; background-color: #f8f9fa; width: 35%; text-align: left; font-size: 11px; text-transform: uppercase;">${label}</th>
        <td style="padding: 12px; border: 1px solid #000; font-size: 13px; font-weight: bold; text-transform: uppercase;">${valStr}</td>
      </tr>
    `;
  });

  return `
    <div style="max-width: 800px; margin: 0 auto; border: 3px solid #001F3F; padding: 40px; background: #fff; font-family: Arial, sans-serif;">
      <div style="text-align: center; border-bottom: 4px solid #001F3F; padding-bottom: 20px; margin-bottom: 30px;">
        <h1 style="color: #001F3F; margin: 0; font-size: 26px; text-transform: uppercase; font-weight: 900;">K.K. UNIVERSITY - SOETR</h1>
        <h2 style="margin: 10px 0; font-size: 16px; color: #333; text-transform: uppercase; letter-spacing: 2px;">Official ${entry.formType} Record</h2>
        <p style="font-size: 11px; color: #666; margin: 0; font-weight: bold;">Reference ID: ${entry.id} | Date Submitted: ${entry.date}</p>
      </div>
      <table style="width: 100%; border-collapse: collapse;">
        <tbody>
          <tr>
            <th style="padding: 12px; border: 1px solid #000; background-color: #001F3F; color: #fff; text-align: left; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;" colspan="2">Student Particulars & Form Data</th>
          </tr>
          ${rows}
        </tbody>
      </table>
      <div style="margin-top: 60px; text-align: center; font-size: 10px; color: #888; border-top: 2px dashed #ccc; padding-top: 15px; text-transform: uppercase; letter-spacing: 1px;">
        This document is electronically generated by the K.K. University SOETR Master Hub.<br/>
        Data Integrity Verified.
      </div>
    </div>
  `;
};
export const AdminDashboard: React.FC = () => {
  const { 
    logout, submissions, deleteSubmission, 
    uploadedContent, publishContent, toggleButtonLock, buttonLocks,
    formTimelines, updateFormTimeline, updateAllFormTimelines,
    dataRecords, deleteDataRecord,
    liveUpdatesText, updateLiveUpdatesText
  } = useAuth();

  const [tickerInput, setTickerInput] = useState(liveUpdatesText);
  const [personnelSearch, setPersonnelSearch] = useState('');
  const [personnelProgramme, setPersonnelProgramme] = useState('');
  
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<string>('overview');
  const [dbCategory, setDbCategory] = useState('Data Entry');
  const [viewingSubmission, setViewingSubmission] = useState<MockSubmission | null>(null);
  const [isActionLoading, setIsActionLoading] = useState(false);
  const [dbFilters, setDbFilters] = useState({ programme: '', session: '', year: '', semester: '' });
  
  const [uploadData, setUploadData] = useState<Partial<UploadedContent>>({ category: 'Notice', programme: 'All Programmes', year: 'All Years', semester: 'All Semesters' });

  const handleLogout = () => { logout(); navigate('/'); };

  const onPublishArtifact = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!uploadData.title || !uploadData.fileData) return alert("Validation Error: Please provide a title and document artifact.");
    setIsActionLoading(true);
    publishContent({ 
      ...uploadData, 
      id: Date.now().toString(), 
      datePublished: new Date().toLocaleDateString('en-GB') 
    } as UploadedContent);
    setIsActionLoading(false);
    alert("Repository Synchronized: Artifact is now visible to students.");
    setUploadData({ category: 'Notice', programme: 'All Programmes', year: 'All Years', semester: 'All Semesters' });
  };

  const exportRegistry = () => {
    let filteredSubmissions = submissions.filter(s => s.formType === dbCategory);

    // Apply the filters to the export data
    if (dbFilters.programme) filteredSubmissions = filteredSubmissions.filter(s => s.programme === dbFilters.programme);
    if (dbFilters.session) filteredSubmissions = filteredSubmissions.filter(s => s.data?.session === dbFilters.session);
    if (dbFilters.year) filteredSubmissions = filteredSubmissions.filter(s => s.data?.year === dbFilters.year);
    if (dbFilters.semester) filteredSubmissions = filteredSubmissions.filter(s => s.data?.semester === dbFilters.semester);

    if (filteredSubmissions.length === 0) {
      return alert("Registry Empty: No records found for the selected filters.");
    }

    let dataToExport: any[] = [];

    if (dbCategory === 'Internship Letter') {
      dataToExport = filteredSubmissions.map(sub => ({
        'Reference No.': sub.id,
        'Enrollment No': sub.enrollmentNo,
        'Programme': sub.programme,
        'Session': sub.data?.session || 'N/A',
        'Year': sub.data?.year || 'N/A',
        'Semester': sub.data?.semester || 'N/A',
        'Name of Candidate': sub.name,
        'Father’s Name': sub.data?.fatherName || 'N/A',
        'Mother’s Name': sub.data?.motherName || 'N/A',
        'Mobile No.': sub.data?.mobile || 'N/A',
        'Email Id': sub.data?.email || 'N/A',
        'Address': sub.data?.address || 'N/A',
        'Alloted School': sub.data?.internshipSchool || 'N/A',
        'SIP Started Date': sub.data?.internshipStartDate || 'N/A',
        'SIP Finishing Date': sub.data?.internshipEndDate || 'N/A',
        'Photo': sub.data?.photoUrl ? 'Uploaded' : 'Not Uploaded'
      }));
    } else if (dbCategory === 'Exam Form') {
      dataToExport = filteredSubmissions.map(sub => {
        const theory = sub.data?.theoryInputs || [];
        const practical = sub.data?.practicalInputs || [];
        const allSubjects = [...theory, ...practical].filter((s: any) => s.code || s.name);
        
        return {
          'Reference No.': sub.id,
          'Enrollment No': sub.enrollmentNo,
          'Programme': sub.programme,
          'Session': sub.data?.session || 'N/A',
          'Year': sub.data?.year || 'N/A',
          'Semester': sub.data?.semester || 'N/A',
          'Name of Candidate': sub.name,
          'Father’s Name': sub.data?.fatherName || 'N/A',
          'Mother’s Name': sub.data?.motherName || 'N/A',
          'Mobile No.': sub.data?.mobile || 'N/A',
          'Email Id': sub.data?.email || 'N/A',
          'Course/Subject Code': allSubjects.map((s: any) => s.code).join('\n'),
          'Course/Subject Name': allSubjects.map((s: any) => s.name).join('\n'),
          'Signature': sub.data?.studentSignatureUrl ? 'Uploaded' : 'Not Uploaded',
          'Photo': sub.data?.photoUrl ? 'Uploaded' : 'Not Uploaded'
        };
      });
    } else if (dbCategory === 'Data Entry') {
      dataToExport = filteredSubmissions.map(sub => {
        const edu = sub.data?.eduDetails || [];
        const eduFormatted = edu.map((e: any, i: number) => {
          if (!e.year && !e.board && !e.result) return '';
          return `${i+1}. ${e.programme} | Stream: ${e.subject} | Board: ${e.board} | Year: ${e.year} | Result: ${e.result}%`;
        }).filter(Boolean).join('\n');

        return {
          'Reference No.': sub.id,
          'Enrollment No': sub.enrollmentNo,
          'Programme': sub.programme,
          'Session': sub.data?.session || 'N/A',
          'Year': sub.data?.year || 'N/A',
          'Semester': sub.data?.semester || 'N/A',
          'Name of Candidate': sub.name,
          'Father’s Name': sub.data?.fatherName || 'N/A',
          'Mother’s Name': sub.data?.motherName || 'N/A',
          'Mobile No.': sub.data?.mobile || 'N/A',
          'Email Id': sub.data?.email || 'N/A',
          'Cultural Interest': (sub.data?.culturalInterests || []).join('\n'),
          'Sports Interest': (sub.data?.sportsInterests || []).join('\n'),
          'Photo': sub.data?.photoUrl ? 'Uploaded' : 'Not Uploaded',
          'Educational Qualification': eduFormatted
        };
      });
    } else {
      dataToExport = filteredSubmissions.map(sub => {
        const flatData: any = {
          'Reference ID': sub.id,
          'Submission Date': sub.date,
          'Enrollment Number': sub.enrollmentNo,
          'Student Name': sub.name,
          'Programme': sub.programme,
          'Form Type': sub.formType
        };
        if (sub.data) {
          Object.keys(sub.data).forEach(key => {
            if (['photoUrl', 'studentSignatureUrl', 'fileData'].includes(key)) return;
            const formattedKey = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()).trim();
            flatData[formattedKey] = typeof sub.data[key] === 'object' ? JSON.stringify(sub.data[key]) : sub.data[key];
          });
        }
        return flatData;
      });
    }

    const worksheet = XLSX.utils.json_to_sheet(dataToExport);
    const wscols = Object.keys(dataToExport[0]).map(() => ({ wch: 25 }));
    worksheet['!cols'] = wscols;

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Records");
    XLSX.writeFile(workbook, `SOETR_${dbCategory.replace(/\s+/g, '_')}_Registry.xlsx`);
    alert(`Excel Export Complete: ${dbCategory}`);
  };

  const getFilteredSubmissions = () => {
    return submissions.filter(s => s.formType === dbCategory)
      .filter(s => !dbFilters.programme || s.programme === dbFilters.programme)
      .filter(s => !dbFilters.session || s.data?.session === dbFilters.session)
      .filter(s => !dbFilters.year || s.data?.year === dbFilters.year)
      .filter(s => !dbFilters.semester || s.data?.semester === dbFilters.semester);
  };

  const generateBulkWord = () => {
    const filtered = getFilteredSubmissions();
    if (filtered.length === 0) return alert("No records match the current filter.");
    const htmlContent = filtered.map(entry => getOfficialDocumentHTML(entry)).join('<br clear="all" style="page-break-before:always" />');
    const blob = new Blob(['\ufeff', `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Bulk Export</title></head><body>${htmlContent}</body></html>`], { type: 'application/msword' });
    const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `SOETR_Bulk_${dbCategory}.doc`; link.click();
  };

  const generateBulkPDF = () => {
    const filtered = getFilteredSubmissions();
    if (filtered.length === 0) return alert("No records match the current filter.");
    const htmlContent = filtered.map(entry => getOfficialDocumentHTML(entry)).join('<div style="page-break-after: always;"></div>');
    const printWindow = window.open('', '_blank');
    printWindow?.document.write(`<html><head><style>@media print { @page { margin: 10mm; } body { background: #fff; -webkit-print-color-adjust: exact; } }</style></head><body style="font-family: Arial;">${htmlContent}<script>window.onload=function(){setTimeout(function(){window.print();window.close();},500);};</script></body></html>`);
    printWindow?.document.close();
  };

  const generateIndividualWord = (entry: MockSubmission) => {
    const htmlContent = getOfficialDocumentHTML(entry);
    const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>${entry.formType}</title></head>
      <body>${htmlContent}</body>
      </html>
    `;
    const blob = new Blob(['\ufeff', content], { type: 'application/msword' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `SOETR_${entry.formType.replace(/\s+/g, '_')}_${entry.enrollmentNo}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const generateIndividualPDF = (entry: MockSubmission) => {
    const htmlContent = getOfficialDocumentHTML(entry);
    const printWindow = window.open('', '_blank');
    if (!printWindow) return alert("Please allow pop-ups to generate PDF.");
    
    printWindow.document.write(`
      <html>
      <head>
        <title>${entry.id} - ${entry.formType}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; background: #525659; display: flex; justify-content: center; padding: 20px; }
          @media print {
            @page { margin: 10mm; }
            body { background: #fff; padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          }
        </style>
      </head>
      <body>
        ${htmlContent}
        <script>
          window.onload = function() {
            setTimeout(function() { window.print(); window.close(); }, 500);
          };
        </script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  const renderSubmissionArtifact = (sub: MockSubmission) => {
    const d = sub.data;
    return (
      <div className="bg-white p-12 w-full max-w-[210mm] border-4 border-kku-blue rounded-3xl shadow-2xl opacity-100 font-serif">
         <div className="flex justify-between items-center border-b-4 border-kku-gold pb-6 mb-8">
            <Logo className="w-20 h-20" />
            <div className="text-right">
               <h1 className="text-2xl font-black uppercase text-kku-blue m-0">Institutional Artifact</h1>
               <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{sub.formType} | {sub.id}</p>
            </div>
         </div>
         <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                   {[
                     { id: 'notice-board', label: 'Notice Board' },
                     { id: 'assignments', label: 'Assignment Questions' },
                     { id: 'timetable', label: 'Academic Time-Table' },
                     { id: 'question-bank', label: 'Question Bank' },
                     { id: 'study-materials', label: 'Study Materials' },
                     { id: 'result', label: 'Exam Results' },
                     { id: 'data-entry', label: 'Data Entry Form' },
                     { id: 'exam', label: 'Examination Form' },
                     { id: 'internship', label: 'Internship Letter' },
                     { id: 'leave', label: 'Leave Application' },
                     { id: 'grievance', label: 'Fill Grievance' }
                   ].map(btn => (
                     <div key={btn.id} className="flex flex-col sm:flex-row items-center justify-between p-6 border-4 border-gray-100 rounded-[2rem] bg-gray-50 hover:border-kku-blue/20 transition-all gap-4">
                       <span className="font-black uppercase text-sm tracking-widest text-kku-blue">{btn.label}</span>
                       <button 
                         onClick={() => toggleButtonLock(btn.id, !buttonLocks[btn.id])}
                         className={`px-8 py-4 rounded-full font-black text-[10px] uppercase tracking-widest transition-all shadow-md border-2 w-full sm:w-auto ${
                           buttonLocks[btn.id] 
                           ? 'bg-red-100 text-red-700 border-red-300 hover:bg-red-700 hover:text-white' 
                           : 'bg-green-100 text-green-700 border-green-300 hover:bg-green-700 hover:text-white'
                         }`}
                       >
                         {buttonLocks[btn.id] ? '🔒 LOCKED' : '🔓 UNLOCKED'}
                       </button>
                     </div>
                   ))}
                 </div>
         </div>
    );
  };

  const btnCls = (isActive: boolean) => `w-full flex items-center gap-6 px-8 py-5 rounded-2xl font-black uppercase text-[10px] tracking-[0.2em] transition-all mb-4 ${isActive ? 'bg-kku-gold text-kku-blue shadow-[0_20px_50px_rgba(212,175,55,0.3)] scale-[1.05] z-10 border-2 border-white' : 'hover:bg-white/10 text-white/50 hover:text-white border-2 border-transparent'}`;
  const inputCls = "w-full border-2 border-black p-3 font-bold uppercase rounded-xl focus:ring-4 focus:ring-kku-gold/20 outline-none text-xs bg-white text-black";
  const labelCls = "block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1.5 ml-1";

  return (
    <div className="min-h-screen bg-gray-50 flex font-sans overflow-hidden opacity-100">
      <aside className="bg-[#000F1F] text-white w-80 shrink-0 border-r-8 border-kku-gold flex flex-col z-[60] shadow-[15px_0_60px_rgba(0,0,0,0.5)]">
        <div className="p-10 text-center border-b border-white/5 bg-black/20">
          <Logo className="w-16 h-16 mb-4 mx-auto" />
          <h1 className="text-kku-gold font-serif text-2xl font-black uppercase tracking-tighter">Admin Hub</h1>
          <p className="text-[8px] font-bold text-white/30 uppercase tracking-[0.4em]">SOETR v10.0 MASTER</p>
        </div>
        <nav className="flex-1 overflow-y-auto p-6 custom-scrollbar">
          {NAV_ITEMS.map(item => (
            <button key={item.id} onClick={() => setActiveTab(item.id)} className={btnCls(activeTab === item.id)}>
              <svg className="w-5 h-5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d={item.icon} /></svg>
              {item.label}
            </button>
          ))}
        </nav>
        <div className="p-8 bg-black/20 border-t border-white/5">
          <button onClick={handleLogout} className="w-full bg-red-800/20 text-red-500 border-2 border-red-800/30 py-4 rounded-2xl font-black uppercase text-[9px] tracking-widest hover:bg-red-800 hover:text-white transition-all shadow-xl">Secure Sign Out</button>
        </div>
      </aside>

      <main className="flex-1 flex flex-col bg-white overflow-y-auto custom-scrollbar">
        <header className="bg-white border-b-4 border-gray-100 px-12 py-10 flex justify-between items-center sticky top-0 z-50 shadow-sm">
          <div>
            <h2 className="text-2xl font-black uppercase tracking-[0.2em] text-kku-blue">{activeTab} Environment</h2>
            <p className="text-[9px] font-black uppercase text-gray-400 tracking-widest mt-1">Authorized Command Center Gateway</p>
          </div>
          <div className="flex items-center gap-6">
             <div className="flex items-center gap-3 bg-green-50 px-4 py-2 rounded-full border border-green-100">
                <span className="w-2.5 h-2.5 bg-green-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(34,197,94,0.5)]"></span>
                <span className="text-[9px] font-black uppercase text-green-700">Database Live</span>
             </div>
          </div>
        </header>

        <div className="p-12 space-y-12 pb-32">
          {activeTab === 'overview' && (
            <div className="animate-fadeIn space-y-12">
               <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
                  {[ 
                    { label: 'Personnel Records', count: dataRecords.length, color: 'text-blue-600', sub: 'Verified Entities' },
                    { label: 'Registry Submissions', count: submissions.length, color: 'text-green-600', sub: 'Student Inbound' },
                    { label: 'Infrastructure Artifacts', count: uploadedContent.length, color: 'text-kku-gold', sub: 'Digital Repository' }
                  ].map((stat, i) => (
                    <div key={i} className="bg-white border-4 border-black p-10 rounded-[3rem] shadow-[20px_20px_0_rgba(0,31,63,0.05)] transform transition hover:-translate-y-2 hover:shadow-[30px_30px_0_rgba(0,31,63,0.1)]">
                      <p className="text-[10px] font-black uppercase text-gray-400 mb-2 tracking-widest">{stat.label}</p>
                      <h3 className={`text-7xl font-black ${stat.color} leading-none mb-4`}>{stat.count}</h3>
                      <p className="text-[9px] font-black uppercase text-gray-300 tracking-widest">{stat.sub}</p>
                    </div>
                  ))}
               </div>
               <div className="bg-kku-blue/5 border-4 border-black rounded-[4rem] p-16 relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-64 h-64 bg-kku-blue opacity-[0.03] rounded-full -mr-32 -mt-32"></div>
                  <h3 className="text-4xl font-serif font-black uppercase text-kku-blue mb-8 border-b-2 border-kku-gold pb-4 inline-block">Institutional Protocol</h3>
                  <p className="text-gray-600 font-bold text-xl max-w-4xl leading-relaxed">
                    Welcome to the SOETR Master Hub. This environment facilitates enterprise-grade management of digital signatures, portal visibility, and academic repositories. All actions performed within this workspace are logged for institutional security compliance.
                  </p>
               </div>
            </div>
          )}

          {activeTab === 'personnel' && (
            <div className="animate-fadeIn space-y-10">
               <div className="flex flex-col md:flex-row justify-between items-center bg-gray-50 p-8 rounded-[3rem] border-2 border-black/5 gap-6">
                  <div>
                    <h3 className="text-3xl font-black uppercase text-kku-blue">Personnel Hub</h3>
                  </div>
                  <div className="flex gap-4 w-full md:w-auto">
                    <input type="text" placeholder="Search ID or Name..." value={personnelSearch} onChange={e => setPersonnelSearch(e.target.value)} className={inputCls} />
                    <select value={personnelProgramme} onChange={e => setPersonnelProgramme(e.target.value)} className={inputCls}>
                      <option value="">ALL PROGRAMMES</option>
                      {PROGRAMMES.map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                    <button onClick={() => navigate('/admin/data-entry')} className="bg-kku-blue text-white px-8 py-3 rounded-[2.5rem] font-black uppercase text-xs shadow-xl border-2 border-white hover:bg-black transition-all whitespace-nowrap">+ New</button>
                  </div>
               </div>
               <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                  {dataRecords
                    .filter(r => r.basicInfo.name.toLowerCase().includes(personnelSearch.toLowerCase()) || r.basicInfo.enrollmentNo.toLowerCase().includes(personnelSearch.toLowerCase()))
                    .filter(r => personnelProgramme === '' || r.basicInfo.programme === personnelProgramme)
                    .map(rec => (
                    <div key={rec.id} onClick={() => navigate('/admin/data-entry', { state: { editData: rec } })} className="bg-white border-2 border-black p-8 rounded-[3rem] shadow-xl group hover:shadow-2xl transition-all relative cursor-pointer hover:border-kku-blue">
                       <div className="flex justify-between mb-8">
                          <span className="bg-kku-blue text-white px-4 py-1.5 rounded-xl text-[9px] font-black uppercase tracking-widest">{rec.domain}</span>
                          <button onClick={(e) => { e.stopPropagation(); if(window.confirm('Delete record?')) deleteDataRecord(rec.id); }} className="text-red-700 text-xs font-black uppercase hover:underline opacity-40 group-hover:opacity-100 transition-all">Erase</button>
                       </div>
                       <h4 className="text-2xl font-black uppercase text-kku-blue leading-tight mb-2">{rec.basicInfo.name}</h4>
                       <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest border-l-4 border-kku-gold pl-3">{rec.basicInfo.enrollmentNo}</p>
                       <div className="mt-6 text-[9px] font-black text-gray-400 uppercase text-right opacity-0 group-hover:opacity-100 transition-opacity">Click to Edit Form ➔</div>
                    </div>
                  ))}
               </div>
            </div>
          )}

          {activeTab === 'registry' && (
            <div className="animate-fadeIn space-y-8">
              <div className="bg-gray-50 p-12 rounded-[4rem] border-4 border-black/5 flex flex-col gap-8 shadow-inner">
                <div className="flex flex-wrap gap-6 items-center justify-between">
                  <div className="flex flex-wrap gap-3">
                    {SUBMISSION_CATEGORIES.map(cat => (
                      <button key={cat.id} onClick={() => setDbCategory(cat.id)} className={`px-8 py-4 font-black uppercase text-[10px] border-2 rounded-[1.5rem] transition-all tracking-widest ${dbCategory === cat.id ? 'bg-kku-blue text-white border-kku-gold shadow-2xl scale-105' : 'bg-white text-gray-400 border-gray-100 hover:border-black'}`}>{cat.label}</button>
                    ))}
                  </div>
                  <button onClick={exportRegistry} className="bg-green-700 text-white px-10 py-5 rounded-[1.5rem] font-black text-[10px] uppercase border-4 border-white shadow-2xl hover:bg-black transition-all">Export Excel</button>
                  <button onClick={generateBulkWord} className="bg-blue-700 text-white px-8 py-5 rounded-[1.5rem] font-black text-[10px] uppercase shadow-2xl hover:bg-black transition-all">Export Word</button>
<button onClick={generateBulkPDF} className="bg-red-700 text-white px-8 py-5 rounded-[1.5rem] font-black text-[10px] uppercase shadow-2xl hover:bg-black transition-all">Download PDF</button>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6 bg-white p-6 rounded-[2.5rem] border-2 border-black/10">
                  <div>
                    <label className={labelCls}>Programme</label>
                    <select value={dbFilters.programme} onChange={e => setDbFilters({...dbFilters, programme: e.target.value})} className={inputCls}>
                      <option value="">All Programmes</option>
                      {PROGRAMMES.map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className={labelCls}>Session</label>
                    <select value={dbFilters.session} onChange={e => setDbFilters({...dbFilters, session: e.target.value})} className={inputCls}>
                      <option value="">All Sessions</option>
                      <option value="2024-2026">2024-2026</option>
                      <option value="2023-2025">2023-2025</option>
                    </select>
                  </div>
                  <div>
                    <label className={labelCls}>Year</label>
                    <select value={dbFilters.year} onChange={e => setDbFilters({...dbFilters, year: e.target.value})} className={inputCls}>
                      <option value="">All Years</option>
                      <option value="First Year">First Year</option>
                      <option value="Second Year">Second Year</option>
                    </select>
                  </div>
                  <div>
                    <label className={labelCls}>Semester</label>
                    <select value={dbFilters.semester} onChange={e => setDbFilters({...dbFilters, semester: e.target.value})} className={inputCls}>
                      <option value="">All Semesters</option>
                      <option value="First Semester">First Semester</option>
                      <option value="Second Semester">Second Semester</option>
                      <option value="Third Semester">Third Semester</option>
                      <option value="Fourth Semester">Fourth Semester</option>
                    </select>
                  </div>
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
                {submissions
                  .filter(s => s.formType === dbCategory)
                  .filter(s => !dbFilters.programme || s.programme === dbFilters.programme)
                  .filter(s => !dbFilters.session || s.data?.session === dbFilters.session)
                  .filter(s => !dbFilters.year || s.data?.year === dbFilters.year)
                  .filter(s => !dbFilters.semester || s.data?.semester === dbFilters.semester)
                  .map(sub => (
                  <div key={sub.id} className="bg-white border-2 border-black p-10 rounded-[3.5rem] shadow-xl group hover:shadow-2xl transition-all relative overflow-hidden">
                     <div className="flex justify-between items-start mb-8 relative z-10">
                        <span className="text-[9px] font-black text-kku-gold uppercase bg-kku-blue px-4 py-1.5 rounded-full shadow-md">{sub.id}</span>
                        <span className="text-[9px] font-black text-gray-300">{sub.date}</span>
                     </div>
                     <h3 className="text-2xl font-black text-kku-blue uppercase mb-3 relative z-10 leading-none">{sub.name}</h3>
                     <p className="text-[10px] font-bold text-gray-500 uppercase mb-10 border-l-4 border-kku-gold pl-3 relative z-10">{sub.programme}</p>
                     <div className="flex flex-col gap-3 relative z-10 mt-6 pt-6 border-t border-black/5">
                        <div className="flex gap-3">
                          <button onClick={() => generateIndividualWord(sub)} className="flex-1 bg-[#185ABD] text-white py-3 rounded-xl font-black uppercase text-[9px] hover:bg-black transition-all shadow-md border-2 border-transparent">Docx</button>
                          <button onClick={() => generateIndividualPDF(sub)} className="flex-1 bg-[#F40F02] text-white py-3 rounded-xl font-black uppercase text-[9px] hover:bg-black transition-all shadow-md border-2 border-transparent">PDF</button>
                        </div>
                        <div className="flex gap-3">
                          <button onClick={() => setViewingSubmission(sub)} className="flex-1 bg-gray-100 border-2 border-black text-black py-3 rounded-xl font-black uppercase text-[9px] hover:bg-kku-blue hover:text-white transition-all shadow-md">Inspect</button>
                          <button onClick={() => {if(window.confirm('Erase packet?')) deleteSubmission(sub.id);}} className="px-5 border-2 border-red-800 text-red-800 rounded-xl font-black uppercase text-[9px] hover:bg-red-800 hover:text-white transition-all">Del</button>
                        </div>
                     </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'upload' && (
            <div className="animate-fadeIn max-w-4xl mx-auto">
               <div className="bg-white border-4 border-black rounded-[4rem] p-16 shadow-2xl">
                  <h3 className="text-4xl font-serif font-black uppercase text-kku-blue mb-10 border-b-4 border-kku-gold pb-4 inline-block">Repository Management</h3>
                  <form onSubmit={onPublishArtifact} className="space-y-12">
                    <div className="grid grid-cols-2 gap-10">
                       <div><label className={labelCls}>Artifact Category</label><select value={uploadData.category} onChange={e => setUploadData({...uploadData, category: e.target.value})} className={inputCls}>{REPOSITORY_CATEGORIES.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></div>
                       <div><label className={labelCls}>Target Programme</label><select value={uploadData.programme} onChange={e => setUploadData({...uploadData, programme: e.target.value})} className={inputCls}><option>All Programmes</option>{PROGRAMMES.map(p => <option key={p} value={p}>{p}</option>)}</select></div>
                    </div>
                    <div><label className={labelCls}>Artifact Title</label><input required value={uploadData.title || ''} onChange={e => setUploadData({...uploadData, title: e.target.value})} className={inputCls} placeholder="ENTER SECURE TITLE" /></div>
                    <div className="p-20 border-4 border-dashed border-gray-100 rounded-[4rem] text-center relative group hover:border-kku-blue transition-all bg-gray-50/50">
                       <svg className="w-16 h-16 mx-auto mb-6 text-gray-200 group-hover:text-kku-gold transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" /></svg>
                       <p className="font-black text-gray-400 uppercase text-[12px] tracking-[0.3em]">{uploadData.fileName || 'Select PDF/DOCX Artifact'}</p>
                       <input type="file" onChange={(e) => { const f = e.target.files?.[0]; if(f){ const r = new FileReader(); r.onload=(ev)=>setUploadData({...uploadData, fileName:f.name, fileData:ev.target?.result as string, fileSize:(f.size/1024).toFixed(1)+'KB'}); r.readAsDataURL(f); } }} className="absolute inset-0 opacity-0 cursor-pointer" />
                    </div>
                    <button type="submit" disabled={isActionLoading} className="w-full py-12 bg-kku-blue text-white font-black uppercase rounded-[3rem] shadow-2xl hover:bg-black transition-all text-xl tracking-[0.4em] border-4 border-white flex items-center justify-center gap-10 group">
                       {isActionLoading ? <div className="w-8 h-8 border-4 border-white/30 border-t-white rounded-full animate-spin"></div> : (
                         <>
                           Publish to Repository
                           <svg className="w-8 h-8 transition-transform group-hover:translate-x-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
                         </>
                       )}
                    </button>
                  </form>
               </div>
            </div>
          )}
          {activeTab === 'timeline' && (
            <div className="animate-fadeIn max-w-4xl mx-auto">
               <div className="bg-white border-4 border-black rounded-[4rem] p-16 shadow-2xl">
                      {/* LIVE UPDATES TICKER CONTROL */}
              <div className="bg-white rounded-3xl p-6 md:p-8 shadow-xl border-t-4 border-kku-gold mb-10">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-12 h-12 bg-red-100 text-red-700 rounded-full flex items-center justify-center">
                    <span className="w-3 h-3 bg-red-600 rounded-full animate-pulse"></span>
                  </div>
                  <div>
                    <h3 className="text-xl font-black text-[#001F3F] uppercase tracking-wider">Live Updates Ticker</h3>
                    <p className="text-sm text-gray-500 font-medium">Update the scrolling broadcast message on the Home Page.</p>
                  </div>
                </div>
                
                <div className="space-y-4">
                  <textarea
                    value={tickerInput}
                    onChange={(e) => setTickerInput(e.target.value)}
                    placeholder="Type your announcement here... Use ★ and ● for styling."
                    className="w-full h-32 p-4 border-2 border-gray-200 rounded-2xl focus:border-kku-blue focus:ring-4 focus:ring-kku-blue/10 transition-all resize-none font-bold text-gray-700 uppercase"
                  />
                  <div className="flex justify-end">
                    <button 
                      onClick={() => updateLiveUpdatesText(tickerInput)}
                      className="px-8 py-3 bg-[#001F3F] text-white font-black uppercase tracking-widest rounded-full hover:bg-kku-gold hover:text-[#001F3F] transition-colors shadow-lg"
                    >
                      Broadcast Update
                    </button>
                  </div>
                </div>
              </div>
                  <h3 className="text-4xl font-serif font-black uppercase text-kku-blue mb-10 border-b-4 border-kku-gold pb-4 inline-block">Environment Governance</h3>
                  <div className="mb-20 bg-kku-blue/5 p-16 rounded-[4rem] border-4 border-dashed border-kku-blue/20">
                     <div className="flex flex-col md:flex-row items-center justify-between gap-12">
                        <div>
                           <h4 className="text-3xl font-black uppercase text-kku-blue mb-3">Master Override Hub</h4>
                           <p className="text-xs font-bold text-gray-400 uppercase tracking-widest">Global authorization toggle for all student features</p>
                        </div>
                        <div className="flex gap-6 w-full md:w-auto">
                           <button onClick={() => updateAllFormTimelines(true)} className="flex-1 px-12 py-6 bg-green-700 text-white rounded-[2rem] font-black uppercase text-xs shadow-2xl hover:bg-black transition-all border-4 border-white/20 tracking-widest">Authorize All</button>
                           <button onClick={() => updateAllFormTimelines(false)} className="flex-1 px-12 py-6 bg-red-700 text-white rounded-[2rem] font-black uppercase text-xs shadow-2xl hover:bg-black transition-all border-4 border-white/20 tracking-widest">Restrict All</button>
                        </div>
                     </div>
                  </div>
                  <div className="space-y-8">
                    {formTimelines.map(tl => (
                      <div key={tl.formId} className="p-12 bg-gray-50 rounded-[3.5rem] border-2 border-black/5 flex items-center justify-between group hover:bg-white hover:border-kku-blue/40 transition-all shadow-xl hover:shadow-2xl">
                        <div className="flex items-center gap-10">
                           <div className={`w-8 h-8 rounded-full ${tl.isActive ? 'bg-green-500 shadow-[0_0_20px_rgba(34,197,94,1)]' : 'bg-red-500 shadow-[0_0_20px_rgba(239,68,68,1)]'}`}></div>
                           <div>
                             <span className="font-black uppercase text-2xl text-kku-blue block leading-none mb-2">{tl.formName}</span>
                             <span className="text-[11px] font-bold text-gray-400 uppercase tracking-[0.3em]">Protocol Status: {tl.isActive ? 'AUTHORIZED ACCESS' : 'ENVIRONMENT LOCKED'}</span>
                           </div>
                        </div>
                        <button onClick={() => updateFormTimeline({...tl, isActive: !tl.isActive})} className={`px-14 py-6 rounded-[2.5rem] font-black uppercase text-[11px] border-4 transition-all shadow-2xl tracking-widest ${tl.isActive ? 'bg-green-700 text-white border-white/20 hover:bg-black' : 'bg-red-700 text-white border-white/20 hover:bg-black'}`}>
                          {tl.isActive ? 'ACTIVE' : 'LOCKED'}
                        </button>
                      </div>
                    ))}
                  </div>
               </div>
            </div>
          )}
        </div>
      </main>

      {viewingSubmission && (
        <div className="fixed inset-0 z-[100] bg-black/95 backdrop-blur-3xl flex flex-col items-center py-20 px-4 overflow-y-auto animate-fadeIn">
          <div className="w-full max-w-[210mm] mb-16 flex justify-between items-center bg-white p-12 rounded-[4rem] shadow-2xl border-4 border-kku-blue no-print">
            <div><h3 className="text-kku-blue font-black uppercase text-3xl tracking-tighter">Security Audit: {viewingSubmission.id}</h3><p className="text-[11px] font-bold text-gray-400 uppercase tracking-[0.5em] mt-2">Master Archive Entry</p></div>
            <div className="flex gap-4">
              <button onClick={() => generateIndividualWord(viewingSubmission)} className="bg-blue-600 text-white px-8 py-5 rounded-[2.5rem] font-black uppercase text-xs shadow-2xl border-4 border-white hover:bg-black transition-all">Download Word</button>
              <button onClick={() => window.print()} className="bg-kku-blue text-white px-8 py-5 rounded-[2.5rem] font-black uppercase text-xs shadow-2xl border-4 border-white hover:bg-black transition-all">Print PDF</button>
              <button onClick={() => setViewingSubmission(null)} className="bg-red-700 text-white px-8 py-5 rounded-[2.5rem] font-black uppercase text-xs shadow-2xl border-4 border-white hover:bg-black transition-all">Close</button>
            </div>
          </div>
          <div className="opacity-100">{renderSubmissionArtifact(viewingSubmission)}</div>
        </div>
      )}
    </div>
  );
};