
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { StudentFormData } from '../../types';
import { useAuth } from '../../context/AuthContext';
import { PROGRAMMES } from '../../constants';
import { A4FormWrapper } from '../../components/A4FormWrapper';

export const GrievanceForm: React.FC = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState<Partial<StudentFormData>>({
    programme: 'B.Ed.',
    name: '',
    enrollmentNo: '',
    email: '',
    mobile: ''
  });
  const [grievance, setGrievance] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isPrintMode, setIsPrintMode] = useState(false);
  const { addSubmission, generateRefNo } = useAuth();
  const [currentRefNo, setCurrentRefNo] = useState('');

  useEffect(() => {
    setCurrentRefNo(generateRefNo());
    const draft = localStorage.getItem('draft_GrievanceForm');
    if (draft) { try { const p = JSON.parse(draft); setFormData(p.formData || {}); setGrievance(p.grievance || ''); } catch(e) {} }
  }, []);

  const handleVerifyAndSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !grievance) return alert("Please fill mandatory particulars.");
    if (!window.confirm("Initialize Formal Redressal cycle? All details will be saved to the official audit log.")) return;

    setIsSaving(true);
    await new Promise(r => setTimeout(r, 2000));
    addSubmission({ id: currentRefNo, date: new Date().toLocaleDateString(), enrollmentNo: formData.enrollmentNo || '', name: formData.name || '', programme: formData.programme || '', formType: 'Grievance', data: { ...formData, grievance, refNo: currentRefNo } });
    setIsSaving(false);
    alert(`Case Registered! Artifact Ref: ${currentRefNo}`);
    localStorage.removeItem('draft_GrievanceForm');
    navigate('/');
  };

  const FormContent = () => (
    <div className="font-serif space-y-10 p-4">
      <h2 className="text-xl font-black uppercase underline text-center">Formal Case Redressal Statement</h2>
      <div className="grid grid-cols-2 gap-4 border-2 border-black p-8 rounded-[2rem] bg-gray-50 shadow-sm">
         <div className="flex flex-col"><span className="text-[9pt] font-black text-gray-400 uppercase">STUDENT:</span> <span className="font-black uppercase text-[12pt]">{formData.name}</span></div>
         <div className="flex flex-col"><span className="text-[9pt] font-black text-gray-400 uppercase">ID:</span> <span className="font-black uppercase text-[12pt]">{formData.enrollmentNo}</span></div>
         <div className="flex flex-col"><span className="text-[9pt] font-black text-gray-400 uppercase">PROGRAMME:</span> <span className="font-black uppercase text-[12pt]">{formData.programme}</span></div>
         <div className="flex flex-col"><span className="text-[9pt] font-black text-gray-400 uppercase">CASE REF:</span> <span className="font-black uppercase text-[12pt] text-red-800">{currentRefNo}</span></div>
      </div>
      <div className="p-10 border-2 border-black min-h-[550px] whitespace-pre-wrap leading-relaxed text-[11.5pt] font-medium text-justify italic bg-white shadow-inner">
        {grievance}
      </div>
      <p className="italic text-gray-500 text-[10pt] text-center mt-10">Verification Protocol: Verified and Synchronized Artifact Generated by SOETR Digital Hub.</p>
    </div>
  );

  if (isPrintMode) {
    return (
      <A4FormWrapper title="Official Case Redressal Artifact" pages={[{ title: "Grievance Statement Record", content: <FormContent />, refNo: currentRefNo }]}>
        <button onClick={() => setIsPrintMode(false)} className="no-print fixed bottom-10 right-10 bg-kku-blue text-white px-10 py-4 rounded-3xl font-black uppercase shadow-2xl border-4 border-white z-[100]">Exit Preview</button>
      </A4FormWrapper>
    );
  }

  const labelCls = "block text-[11px] font-black text-gray-400 uppercase mb-2 ml-2";

  return (
    <div className="min-h-screen bg-gray-100 py-12 px-4 md:px-8">
      <div className="max-w-5xl mx-auto bg-white border-2 border-black rounded-[5rem] shadow-[40px_40px_0_rgba(185,28,28,1)] overflow-hidden">
        <div className="bg-red-700 text-white p-12 md:p-20 flex justify-between items-center relative overflow-hidden">
          <div className="relative z-10">
            <h1 className="text-5xl md:text-6xl font-serif font-black uppercase tracking-tighter">Redressal</h1>
            <p className="text-red-100 font-bold uppercase text-[10px] mt-4 tracking-[0.4em] bg-white/10 px-8 py-2 rounded-full inline-block">Official Grievance Portal</p>
          </div>
          <button onClick={() => setIsPrintMode(true)} className="bg-white/10 border-2 border-white/20 px-8 py-3 rounded-2xl font-black text-xs uppercase hover:bg-white hover:text-red-700 transition-all shadow-xl">Print Record</button>
        </div>

        <form onSubmit={handleVerifyAndSave} className="p-8 md:p-24 space-y-12">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
             <div><label className={labelCls}>Legal Name</label><input required value={formData.name || ''} onChange={e => setFormData({...formData, name: e.target.value})} className="soetr-input" /></div>
             <div><label className={labelCls}>Admission ID</label><input required value={formData.enrollmentNo || ''} onChange={e => setFormData({...formData, enrollmentNo: e.target.value})} className="soetr-input" placeholder="KKU/SOETR/XXXX" /></div>
             <div><label className={labelCls}>Academic Track</label><select value={formData.programme} onChange={e => setFormData({...formData, programme: e.target.value})} className="soetr-input">{PROGRAMMES.map(p => <option key={p}>{p}</option>)}</select></div>
             <div><label className={labelCls}>Case Artifact ID</label><input disabled value={currentRefNo} className="soetr-input bg-gray-50 border-dashed text-red-800" /></div>
          </div>
          <div><label className={labelCls}>Formal Case Statement</label><textarea required value={grievance} onChange={e => setGrievance(e.target.value)} className="soetr-input h-96 normal-case p-10 leading-relaxed shadow-xl text-justify" placeholder="Detail the grievance/incident cycle..." /></div>
          <div className="mt-20 flex flex-col items-center">
            <button type="submit" disabled={isSaving} className="w-full max-w-4xl py-12 bg-red-700 text-white font-black uppercase tracking-[0.3em] border-4 border-white shadow-2xl text-2xl flex items-center justify-center gap-6 transform transition active:scale-95">
              {isSaving && <div className="w-10 h-10 border-8 border-white/30 border-t-white rounded-full animate-spin"></div>}
              {isSaving ? 'Synchronizing Case...' : 'Verify & Synchronize Record'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
